import os
AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
AWS_REGION = "AWS_REGION"
S3_TRAINING_BUCKET_NAME = "bsb4018-rec-sys-app"
S3_FEAST_FEATURE_STORE_BUCKET = "feast-fs-registries-bsb4018"
S3_ENTITY_DATA_STORE_BUCKET = "rec-sys-app-bsb4-entity-data"