import os
AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
AWS_REGION = "AWS_REGION"
S3_TRAINING_BUCKET_NAME = "bsb4018-rec-sys-app"
S3_FEATURE_REGISTRY_BUCKET_NAME = "bsb4018rec-sys-feastfs"