import os
FEAST_FEATURE_STORE_REPO_NAME = "rec_sys_fs"
FEAST_FEATURE_STORE_REPO_PATH = os.path.join(FEAST_FEATURE_STORE_REPO_NAME)
ENTITY_DATA_FOLDER_NAME = "data"
INTERACTIONS_ENTITY_FILE_NAME = "interaction.parquet"
INTERACTIONS_DATA_FILE_PATH = os.path.join(ENTITY_DATA_FOLDER_NAME,INTERACTIONS_ENTITY_FILE_NAME)
