import os
FEAST_FEATURE_STORE_REPO_PATH = os.getenv("FEAST_FEATURE_STORE_REPO_PATH")
INTERACTIONS_DATA_FILE_PATH = os.getenv("INTERACTIONS_DATA_FILE_PATH")
COURSES_DATA_FILE_PATH = os.getenv("COURSES_DATA_FILE_PATH")
USERS_DATA_FILE_PATH = os.getenv("USERS_DATA_FILE_PATH")